class CreateCategories < ActiveRecord::Migration
  def change
    create_table :categories do |t|
      t.string :name
      t.string :slug
      t.string :ancestry, index: true
      t.integer :status, default: 1
    end

    dad = Category.create(name:'Feminino')

      child = dad.children.create(name: 'Calçados')
        child.children.create(name: 'Alpargatas')
        child.children.create(name: 'Ankle boot')
        child.children.create(name: 'Botas')
        child.children.create(name: 'Chinelos')
        child.children.create(name: 'Mocassim')
        child.children.create(name: 'Peep toe')
        child.children.create(name: 'Rasteirinhas')
        child.children.create(name: 'Sandálias')
        child.children.create(name: 'Sapatos')
        child.children.create(name: 'Scarpins')
        child.children.create(name: 'Tênis')

      child = dad.children.create(name: 'Roupas')
        child.children.create(name: 'Blusa')
        child.children.create(name: 'Calças')
        child.children.create(name: 'Calça flare')
        child.children.create(name: 'Camisas')
        child.children.create(name: 'Camisetas')
        child.children.create(name: 'Casacos e jaquetas')
        child.children.create(name: 'Lingeries')
        child.children.create(name: 'Soutiens')
        child.children.create(name: 'Bojos')
        child.children.create(name: 'Calcinhas')
        child.children.create(name: 'Malhas e suéters')
        child.children.create(name: 'Moda praia')
        child.children.create(name: 'Bikinis')
        child.children.create(name: 'Maiôs')
        child.children.create(name: 'Regatas')
        child.children.create(name: 'Saias')
        child.children.create(name: 'Shosts e bermudas')
        child.children.create(name: 'Vestidos')

      child = dad.children.create(name: 'Bolsas e acessórios')
        child.children.create(name: 'Armação de óculos')
        child.children.create(name: 'Bijuterias')
        child.children.create(name: 'Bolsas')
        child.children.create(name: 'Brincos')
        child.children.create(name: 'Carteiras')
        child.children.create(name: 'Cintos')
        child.children.create(name: 'Mochilas e malas')
        child.children.create(name: 'Nécessaires')
        child.children.create(name: 'Óculos de sol')
        child.children.create(name: 'Pulseiras')
        child.children.create(name: 'Relógios')

      child = dad.children.create(name: 'Esporte')
        child.children.create(name: 'Bolsas/Mochilas')
        child.children.create(name: 'Calças moletom')
        child.children.create(name: 'Calças legging')
        child.children.create(name: 'Camisetas')
        child.children.create(name: 'Jaquetas/Agasalhos')
        child.children.create(name: 'Moda Praia')
        child.children.create(name: 'Óculos')
        child.children.create(name: 'Saias')
        child.children.create(name: 'Tênis')
        child.children.create(name: 'Tops')
        child.children.create(name: 'Vestidos')

      child = dad.children.create(name: 'Perfumes e beleza')
        child.children.create(name: 'Cabelos')
        child.children.create(name: 'Corpo e banho')
        child.children.create(name: 'Esmalte')
        child.children.create(name: 'Kits e presentes')
        child.children.create(name: 'Maquiagem')
        child.children.create(name: 'Perfumes')
        child.children.create(name: 'Protetor solar')
        child.children.create(name: 'Sombra')
        child.children.create(name: 'Tratamento')

    dad = Category.create(name:'Masculino')

      child = dad.children.create(name: 'Calçados')
        child.children.create(name: 'Botas')
        child.children.create(name: 'Chinelos')
        child.children.create(name: 'Mocassins')
        child.children.create(name: 'Sandálias')
        child.children.create(name: 'Sapatênis')
        child.children.create(name: 'Sapato Social')
        child.children.create(name: 'Sapato Casual')
        child.children.create(name: 'Tênis')

      child = dad.children.create(name: 'Roupas')
        child.children.create(name: 'Bermudas')
        child.children.create(name: 'Bermudas Jeans')
        child.children.create(name: 'Calças Jeans')
        child.children.create(name: 'Calças Sociais')
        child.children.create(name: 'Camisas')
        child.children.create(name: 'Camisetas')
        child.children.create(name: 'Cuecas')
        child.children.create(name: 'Malhas e Suéteres')
        child.children.create(name: 'Moletons')
        child.children.create(name: 'Polos')
        child.children.create(name: 'Sungas')

      child = dad.children.create(name: 'Bolsas e acessórios')
        child.children.create(name: 'Bonés')
        child.children.create(name: 'Chapéus')
        child.children.create(name: 'Carteiras')
        child.children.create(name: 'Cintos')
        child.children.create(name: 'Mochilas e Malas')
        child.children.create(name: 'Necessaires')
        child.children.create(name: 'Óculos de Sol')
        child.children.create(name: 'Pastas')
        child.children.create(name: 'Relógios')

      child = dad.children.create(name: 'Esporte')
        child.children.create(name: 'Bonés')
        child.children.create(name: 'Bermudas')
        child.children.create(name: 'Calças')
        child.children.create(name: 'Camisas de Times')
        child.children.create(name: 'Camisetas')
        child.children.create(name: 'Chuteiras')
        child.children.create(name: 'Jaquetas')
        child.children.create(name: 'Óculos')
        child.children.create(name: 'Polos')
        child.children.create(name: 'Tênis')

      child = dad.children.create(name: 'Perfumes e beleza')
        child.children.create(name: 'Perfumes')
        child.children.create(name: 'Cabelos')
        child.children.create(name: 'Hidratantes')
        child.children.create(name: 'Modelador')

    dad = Category.create(name:'Infantil')

      child = dad.children.create(name: 'Calçados')
        child.children.create(name: 'Botas')
        child.children.create(name: 'Chinelos')
        child.children.create(name: 'Sandálias')
        child.children.create(name: 'Sapatilhas')
        child.children.create(name: 'Sapatos')
        child.children.create(name: 'Tênis')

      child = dad.children.create(name: 'Roupas')
        child.children.create(name: 'Bermudas e Shorts')
        child.children.create(name: 'Blusas e Camisetas')
        child.children.create(name: 'Calças')
        child.children.create(name: 'Conjuntos')
        child.children.create(name: 'Moletons')

      child = dad.children.create(name: 'Bolsas e acessórios')
        child.children.create(name: 'Artigo de Bebê')
        child.children.create(name: 'Bolsas Maternidade')
        child.children.create(name: 'Bonés e Chapeus')
        child.children.create(name: 'Cintos')
        child.children.create(name: 'Lancheiras')
        child.children.create(name: 'Mochilas e Malas')

      child = dad.children.create(name: 'Esporte')
        child.children.create(name: 'Roupas')
        child.children.create(name: 'Tênis')
        child.children.create(name: 'Brinquedos')

      child = dad.children.create(name: 'Perfumes e beleza')
        child.children.create(name: 'Cabelos')
        child.children.create(name: 'Corpo e banho')
        child.children.create(name: 'Perfumes')

  end
end
